CREATE TABLE todo(
	todo_id SERIAL PRIMARY KEY NOT NULL,
	title VARCHAR(256),
	status VARCHAR(256),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE subtask(
   id SERIAL PRIMARY KEY NOT NULL,
	todo_id SERIAL NOT NULL REFERENCES todo(todo_id),
	title VARCHAR(256),
	status VARCHAR(256),
	created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);